//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDay.Maui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainingDay.Maui.Resources.Strings.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolge.
        /// </summary>
        internal static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training hinzufügen.
        /// </summary>
        internal static string AddTrainingString {
            get {
                return ResourceManager.GetString("AddTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratschläge und Tipps.
        /// </summary>
        internal static string Advice {
            get {
                return ResourceManager.GetString("Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach dem Training ist die Post-Workout-Routine sinnvoll, die Post-Workout-Routine ermöglicht es, den Übergang von hochintensiver Arbeit in einen Ruhezustand zu glätten. Dadurch entlasten Sie den Herzmuskel, der intensiv Blut pumpen muss, um seine Stagnation aus der Muskulatur zu lösen und ihn mit inneren Organen zu versorgen. Geeignet: Leichtes Laufen, sanftes Übergehen ins Gehen (Sie können an Ort und Stelle). Einfache Arbeit auf einem Fahrrad- oder Ellipsentrainer-Simulator, einem Stepper mit sanfter Inte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdviceAfterTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceAfterTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretching vor dem Training ist ein Komplex von Übungen zur Vorbereitung des Körpers auf körperliche Aktivität, die Ihnen helfen, Verletzungen zu vermeiden und die Sitzung so effizient wie möglich durchzuführen. Stretching beschleunigt Stoffwechselprozesse. Das Dehnen vor dem Training verbessert die Durchblutung, wodurch Ihre Muskeln mit Sauerstoff und Nährstoffen gesättigt werden. Dies wird dazu beitragen, die Ausdauer während des Unterrichts zu verbessern. Die erwärmten Muskeln werden besser komprimiert u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdviceBeforeTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceBeforeTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rat.
        /// </summary>
        internal static string AdviceString {
            get {
                return ResourceManager.GetString("AdviceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor: {0}.
        /// </summary>
        internal static string AuthorString {
            get {
                return ResourceManager.GetString("AuthorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück zu den Workouts.
        /// </summary>
        internal static string BackToWorkouts {
            get {
                return ResourceManager.GetString("BackToWorkouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beginnt um.
        /// </summary>
        internal static string BeginsAt {
            get {
                return ResourceManager.GetString("BeginsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaufen.
        /// </summary>
        internal static string BuyString {
            get {
                return ResourceManager.GetString("BuyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absagen.
        /// </summary>
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training abbrechen?.
        /// </summary>
        internal static string CancelTrainingQuestion {
            get {
                return ResourceManager.GetString("CancelTrainingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen werden nach Neustart der Anwendung übernommen.
        /// </summary>
        internal static string ChangesAcceptAfterReboot {
            get {
                return ResourceManager.GetString("ChangesAcceptAfterReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe.
        /// </summary>
        internal static string ChooseGroupOrNewString {
            get {
                return ResourceManager.GetString("ChooseGroupOrNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle eine Aktion.
        /// </summary>
        internal static string ChoseAction {
            get {
                return ResourceManager.GetString("ChoseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letztes Training fortsetzen?.
        /// </summary>
        internal static string ContinueLastTrainingQuestion {
            get {
                return ResourceManager.GetString("ContinueLastTrainingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Kopieren.
        /// </summary>
        internal static string CopiedString {
            get {
                return ResourceManager.GetString("CopiedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewältigungsübungen absolviert.
        /// </summary>
        internal static string CopyExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("CopyExercisesFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        internal static string CopyString {
            get {
                return ResourceManager.GetString("CopyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle neu.
        /// </summary>
        internal static string CreateNewString {
            get {
                return ResourceManager.GetString("CreateNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle superset.
        /// </summary>
        internal static string CreateSuperSetString {
            get {
                return ResourceManager.GetString("CreateSuperSetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell.
        /// </summary>
        internal static string CurrentString {
            get {
                return ResourceManager.GetString("CurrentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeit: {0}.
        /// </summary>
        internal static string CurrentTimeString {
            get {
                return ResourceManager.GetString("CurrentTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tage.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelöscht.
        /// </summary>
        internal static string DeletedString {
            get {
                return ResourceManager.GetString("DeletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übungen löschen?.
        /// </summary>
        internal static string DeleteExercise {
            get {
                return ResourceManager.GetString("DeleteExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übung aus SuperSet löschen?.
        /// </summary>
        internal static string DeleteExerciseFromSuperSetQuestion {
            get {
                return ResourceManager.GetString("DeleteExerciseFromSuperSetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausbildung löschen.
        /// </summary>
        internal static string DeleteTraining {
            get {
                return ResourceManager.GetString("DeleteTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestritten.
        /// </summary>
        internal static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prozentsatz verschiedener Übungen: {0:0.0}%.
        /// </summary>
        internal static string DistinctExercisesPercentFormat {
            get {
                return ResourceManager.GetString("DistinctExercisesPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplikat.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeit: {0:hh\:mm\:ss}.
        /// </summary>
        internal static string ElapsedTimeString {
            get {
                return ResourceManager.GetString("ElapsedTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Trainingsnamen ein und drücken Sie OK.
        /// </summary>
        internal static string EnterTrainingName {
            get {
                return ResourceManager.GetString("EnterTrainingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausführung.
        /// </summary>
        internal static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übung für .
        /// </summary>
        internal static string ExerciseForTypeString {
            get {
                return ResourceManager.GetString("ExerciseForTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übung ist im Training:.
        /// </summary>
        internal static string ExerciseInTrainings {
            get {
                return ResourceManager.GetString("ExerciseInTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übungen.
        /// </summary>
        internal static string ExercisesString {
            get {
                return ResourceManager.GetString("ExercisesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten exportieren.
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterString {
            get {
                return ResourceManager.GetString("FilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor.
        /// </summary>
        internal static string GoalString {
            get {
                return ResourceManager.GetString("GoalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich habs.
        /// </summary>
        internal static string GotItString {
            get {
                return ResourceManager.GetString("GotItString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string GroupingDefaultName {
            get {
                return ResourceManager.GetString("GroupingDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Namen der gruppe ein.
        /// </summary>
        internal static string GroupingEnterNameofGroup {
            get {
                return ResourceManager.GetString("GroupingEnterNameofGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainieren bereits in Default gruppe.
        /// </summary>
        internal static string GroupingTrainingNotInGroup {
            get {
                return ResourceManager.GetString("GroupingTrainingNotInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halbes Jahr.
        /// </summary>
        internal static string HalfYearString {
            get {
                return ResourceManager.GetString("HalfYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helfer.
        /// </summary>
        internal static string HelperString {
            get {
                return ResourceManager.GetString("HelperString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hüften.
        /// </summary>
        internal static string HipsString {
            get {
                return ResourceManager.GetString("HipsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergangene Trainingseinheiten.
        /// </summary>
        internal static string HistoryTrainings {
            get {
                return ResourceManager.GetString("HistoryTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string HourString {
            get {
                return ResourceManager.GetString("HourString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten importieren.
        /// </summary>
        internal static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-App-Kauf.
        /// </summary>
        internal static string InAppPurchase {
            get {
                return ResourceManager.GetString("InAppPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg .
        /// </summary>
        internal static string KilogramsString {
            get {
                return ResourceManager.GetString("KilogramsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte: {0}.
        /// </summary>
        internal static string LastImplementedFormatString {
            get {
                return ResourceManager.GetString("LastImplementedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pfund.
        /// </summary>
        internal static string LbsString {
            get {
                return ResourceManager.GetString("LbsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übungsauswahl starten.
        /// </summary>
        internal static string LetsBuildYourWorkout {
            get {
                return ResourceManager.GetString("LetsBuildYourWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANFANG.
        /// </summary>
        internal static string MakeTrainingString {
            get {
                return ResourceManager.GetString("MakeTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markieren Sie die erforderlichen Übungen und drücken Sie {0}.
        /// </summary>
        internal static string MarkTheRequiredExercisesAndPressFormat {
            get {
                return ResourceManager.GetString("MarkTheRequiredExercisesAndPressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewichtseinheit (kg oder Pfund).
        /// </summary>
        internal static string MeasureWeight {
            get {
                return ResourceManager.GetString("MeasureWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string MinuteString {
            get {
                return ResourceManager.GetString("MinuteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr als Jahr.
        /// </summary>
        internal static string MoreThanYearString {
            get {
                return ResourceManager.GetString("MoreThanYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am häufigsten Tag: {0:0}.
        /// </summary>
        internal static string MostOftenDayFormat {
            get {
                return ResourceManager.GetString("MostOftenDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP Übungen.
        /// </summary>
        internal static string MostPopularExercises {
            get {
                return ResourceManager.GetString("MostPopularExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegungstraining beendet.
        /// </summary>
        internal static string MoveExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("MoveExercisesFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewegen.
        /// </summary>
        internal static string MoveString {
            get {
                return ResourceManager.GetString("MoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        internal static string NameFormatString {
            get {
                return ResourceManager.GetString("NameFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachrichten.
        /// </summary>
        internal static string NewsString {
            get {
                return ResourceManager.GetString("NewsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächste.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Filterbegriff von stimmte mit keiner Übung überein.
        /// </summary>
        internal static string NoExercisesFilterString {
            get {
                return ResourceManager.GetString("NoExercisesFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Übungen. Sie sollten Übung hinzufügen..
        /// </summary>
        internal static string NoExercisesNeedAddNewString {
            get {
                return ResourceManager.GetString("NoExercisesNeedAddNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast noch kein Workout absolviert. Starte dein erstes Workout!.
        /// </summary>
        internal static string NoLastTrainings {
            get {
                return ResourceManager.GetString("NoLastTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Benachrichtigungen. Sie sollten eine Benachrichtigung hinzufügen..
        /// </summary>
        internal static string NoNotificationsString {
            get {
                return ResourceManager.GetString("NoNotificationsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string NoString {
            get {
                return ResourceManager.GetString("NoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht alle Felder ausgefüllt.
        /// </summary>
        internal static string NotAllFieldsEntered {
            get {
                return ResourceManager.GetString("NotAllFieldsEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch nicht ausgeführt.
        /// </summary>
        internal static string NotExecutedYet {
            get {
                return ResourceManager.GetString("NotExecutedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benachrichtigung.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Workouts abgeschlossen.
        /// </summary>
        internal static string NoTrainingsNeedAddNewString {
            get {
                return ResourceManager.GetString("NoTrainingsNeedAddNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berg.
        /// </summary>
        internal static string OneMounthString {
            get {
                return ResourceManager.GetString("OneMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale Wochen mit Training: {0:0}.
        /// </summary>
        internal static string OneTrainingPerWeekCountFormat {
            get {
                return ResourceManager.GetString("OneTrainingPerWeekCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An diesen Tagen.
        /// </summary>
        internal static string OnTheseDays {
            get {
                return ResourceManager.GetString("OnTheseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oder.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie Ihr neues Gewicht ein. Vielleicht hat sich etwas geändert..
        /// </summary>
        internal static string PleaseEnterYourNewWeight {
            get {
                return ResourceManager.GetString("PleaseEnterYourNewWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdominal.
        /// </summary>
        internal static string PreparedAbdominalString {
            get {
                return ResourceManager.GetString("PreparedAbdominalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starke Arme.
        /// </summary>
        internal static string PreparedArmsStrength {
            get {
                return ResourceManager.GetString("PreparedArmsStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker und geprägter Rücken.
        /// </summary>
        internal static string PreparedBackReady {
            get {
                return ResourceManager.GetString("PreparedBackReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herz.
        /// </summary>
        internal static string PreparedCardioString {
            get {
                return ResourceManager.GetString("PreparedCardioString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        internal static string PreparedFitnessString {
            get {
                return ResourceManager.GetString("PreparedFitnessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starke Beine und Oberschenkel.
        /// </summary>
        internal static string PreparedFootTraining {
            get {
                return ResourceManager.GetString("PreparedFootTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohne Inventar.
        /// </summary>
        internal static string PreparedHomeString {
            get {
                return ResourceManager.GetString("PreparedHomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximaler Oberkörper.
        /// </summary>
        internal static string PreparedMaximumUpperBody {
            get {
                return ResourceManager.GetString("PreparedMaximumUpperBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morgentraining.
        /// </summary>
        internal static string PreparedMorningWorkout {
            get {
                return ResourceManager.GetString("PreparedMorningWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flacher Bauch.
        /// </summary>
        internal static string PreparedNiceStomach {
            get {
                return ResourceManager.GetString("PreparedNiceStomach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training für Anfänger.
        /// </summary>
        internal static string PreparedTrainingForBeginners {
            get {
                return ResourceManager.GetString("PreparedTrainingForBeginners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite Schultern.
        /// </summary>
        internal static string PreparedWideShoulders {
            get {
                return ResourceManager.GetString("PreparedWideShoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertungs App.
        /// </summary>
        internal static string RateAppString {
            get {
                return ResourceManager.GetString("RateAppString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung.
        /// </summary>
        internal static string RegisterAction {
            get {
                return ResourceManager.GetString("RegisterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen.
        /// </summary>
        internal static string RemoveString {
            get {
                return ResourceManager.GetString("RemoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reps.
        /// </summary>
        internal static string RepetitionsShort {
            get {
                return ResourceManager.GetString("RepetitionsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholungen | Gewicht.
        /// </summary>
        internal static string RepsAndWeightString {
            get {
                return ResourceManager.GetString("RepsAndWeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholungen.
        /// </summary>
        internal static string RepsString {
            get {
                return ResourceManager.GetString("RepsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brechen.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kauf wiederherstellen.
        /// </summary>
        internal static string RestorePurchase {
            get {
                return ResourceManager.GetString("RestorePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast schon lange kein Workout mehr durchgeführt. Vielleicht ist heute dieser Tag?.
        /// </summary>
        internal static string ReturnToTrainingMessage {
            get {
                return ResourceManager.GetString("ReturnToTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerettet.
        /// </summary>
        internal static string SavedString {
            get {
                return ResourceManager.GetString("SavedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string SaveTrainingString {
            get {
                return ResourceManager.GetString("SaveTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Bildschirm sollte während des Trainings eingeschaltet sein.
        /// </summary>
        internal static string ScreenOnWhenImplementing {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivieren, um Batterie zu sparen.
        /// </summary>
        internal static string ScreenOnWhenImplementingTip {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche mit Name.
        /// </summary>
        internal static string SearchByNameString {
            get {
                return ResourceManager.GetString("SearchByNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunden.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string SecondString {
            get {
                return ResourceManager.GetString("SecondString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie Alle.
        /// </summary>
        internal static string SelectAllString {
            get {
                return ResourceManager.GetString("SelectAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSKELN HINZUFÜGEN.
        /// </summary>
        internal static string SelectMusclesString {
            get {
                return ResourceManager.GetString("SelectMusclesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitraum.
        /// </summary>
        internal static string SelectPeriodString {
            get {
                return ResourceManager.GetString("SelectPeriodString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen.
        /// </summary>
        internal static string SelectString {
            get {
                return ResourceManager.GetString("SelectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training:.
        /// </summary>
        internal static string SelectTraining {
            get {
                return ResourceManager.GetString("SelectTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequenz einstellen.
        /// </summary>
        internal static string SetFrequency {
            get {
                return ResourceManager.GetString("SetFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string SettingsString {
            get {
                return ResourceManager.GetString("SettingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainingseinstellungen.
        /// </summary>
        internal static string SettingsTrainingString {
            get {
                return ResourceManager.GetString("SettingsTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geteilt.
        /// </summary>
        internal static string SharedString {
            get {
                return ResourceManager.GetString("SharedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training teilen.
        /// </summary>
        internal static string ShareTrainingString {
            get {
                return ResourceManager.GetString("ShareTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string ShortDescriptionString1 {
            get {
                return ResourceManager.GetString("ShortDescriptionString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige während des Trainings Tipps zum Aufwärmen und Abkühlen.
        /// </summary>
        internal static string ShowAdvicesOnImplementing {
            get {
                return ResourceManager.GetString("ShowAdvicesOnImplementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips anzeigen.
        /// </summary>
        internal static string ShowToolTipsString {
            get {
                return ResourceManager.GetString("ShowToolTipsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überspringen.
        /// </summary>
        internal static string SkipString {
            get {
                return ResourceManager.GetString("SkipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startposition.
        /// </summary>
        internal static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt.
        /// </summary>
        internal static string StopString {
            get {
                return ResourceManager.GetString("StopString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet-Steuerung.
        /// </summary>
        internal static string SuperSetControl {
            get {
                return ResourceManager.GetString("SuperSetControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet erstellt.
        /// </summary>
        internal static string SuperSetCreatedMessage {
            get {
                return ResourceManager.GetString("SuperSetCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um einen Supersatz zu erstellen, benötigen Sie mehr als 2 Übungen.
        /// </summary>
        internal static string SupersetInvalidMessage {
            get {
                return ResourceManager.GetString("SupersetInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet.
        /// </summary>
        internal static string SuperSetString {
            get {
                return ResourceManager.GetString("SuperSetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du dir sicher? Ihre nicht synchronisierten Daten werden gelöscht..
        /// </summary>
        internal static string SynchronizationDownloadingQuestion {
            get {
                return ResourceManager.GetString("SynchronizationDownloadingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Übung ist bereits im Training vorhanden.
        /// </summary>
        internal static string ThisExerciseAlreadyInWorkoutMessage {
            get {
                return ResourceManager.GetString("ThisExerciseAlreadyInWorkoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 month.
        /// </summary>
        internal static string ThreeMounthString {
            get {
                return ResourceManager.GetString("ThreeMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeit.
        /// </summary>
        internal static string TimeString {
            get {
                return ResourceManager.GetString("TimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf diese Schaltfläche, um ein neues Training hinzuzufügen.
        /// </summary>
        internal static string ToolTipAddTrainingButton {
            get {
                return ResourceManager.GetString("ToolTipAddTrainingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Schaltfläche fügt einen Satz für die Übung hinzu (Satz bedeutet, wie viele Wiederholungen Sie die Übung mit einem bestimmten Gewicht machen).
        /// </summary>
        internal static string ToolTipAddWeightAndRepsString {
            get {
                return ResourceManager.GetString("ToolTipAddWeightAndRepsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Taste bricht das Training ab..
        /// </summary>
        internal static string ToolTipCancelImplementingTraining {
            get {
                return ResourceManager.GetString("ToolTipCancelImplementingTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf den gewünschten Muskel, um einen Filter für diese Muskeln anzuwenden.
        /// </summary>
        internal static string ToolTipFilterMuscle {
            get {
                return ResourceManager.GetString("ToolTipFilterMuscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Taste beendet die Übung..
        /// </summary>
        internal static string ToolTipFinishExercise {
            get {
                return ResourceManager.GetString("ToolTipFinishExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um die Reihenfolge der Übungen zu ändern, müssen Sie das Bild der Übung halten und es an die gewünschte Position ziehen..
        /// </summary>
        internal static string ToolTipHoldImageExercises {
            get {
                return ResourceManager.GetString("ToolTipHoldImageExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücken Sie die Taste, um Übungen für das Training auszuwählen.
        /// </summary>
        internal static string ToolTipSelectExercisesToTrainingButton {
            get {
                return ResourceManager.GetString("ToolTipSelectExercisesToTrainingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Schaltfläche überspringt die Übung, diese Übung wird nicht als abgeschlossen angezeigt.
        /// </summary>
        internal static string ToolTipSkipExercise {
            get {
                return ResourceManager.GetString("ToolTipSkipExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf diese Schaltfläche, um Ihr Training zu starten.
        /// </summary>
        internal static string ToolTipStartWorkout {
            get {
                return ResourceManager.GetString("ToolTipStartWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet ist eine Kombination aus zwei oder mehr Übungen, die darauf ausgelegt sind, denselben Muskel oder dieselben Muskeln der Antagonisten zu trainieren. Die gebräuchlichste Art, Supersätze zu verwenden, besteht darin, Muskelgruppen mit unterschiedlichen Funktionen zu trainieren. Zum Beispiel: Bizeps / Trizeps.
        /// </summary>
        internal static string ToolTipSuperSet {
            get {
                return ResourceManager.GetString("ToolTipSuperSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halten Sie ein Training gedrückt, um die Einstellungen anzuzeigen..
        /// </summary>
        internal static string ToolTipTapHoldTraining {
            get {
                return ResourceManager.GetString("ToolTipTapHoldTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgeschlossenen Übungen: {0:0}.
        /// </summary>
        internal static string TotalExercisesFormat {
            get {
                return ResourceManager.GetString("TotalExercisesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verstrichene zeit:.
        /// </summary>
        internal static string TotalTimeSpent {
            get {
                return ResourceManager.GetString("TotalTimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgeschlossenen trainingseinheiten: {0:0}.
        /// </summary>
        internal static string TotalTrainingsFormat {
            get {
                return ResourceManager.GetString("TotalTrainingsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainieren beendet.
        /// </summary>
        internal static string TrainingFinishedString {
            get {
                return ResourceManager.GetString("TrainingFinishedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benachrichtigungen.
        /// </summary>
        internal static string TrainingNotifications {
            get {
                return ResourceManager.GetString("TrainingNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainiereneinheiten.
        /// </summary>
        internal static string TrainingsBaseString {
            get {
                return ResourceManager.GetString("TrainingsBaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainieren.
        /// </summary>
        internal static string TrainingString {
            get {
                return ResourceManager.GetString("TrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zur Gruppe hinzufügen.
        /// </summary>
        internal static string TrainingToGroupString {
            get {
                return ResourceManager.GetString("TrainingToGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus der Gruppe entfernen &quot;{0}&quot;.
        /// </summary>
        internal static string TrainingUnGroupString {
            get {
                return ResourceManager.GetString("TrainingUnGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Monate.
        /// </summary>
        internal static string TwoMonthString {
            get {
                return ResourceManager.GetString("TwoMonthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Wochen.
        /// </summary>
        internal static string TwoWeeksString {
            get {
                return ResourceManager.GetString("TwoWeeksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string VideoString {
            get {
                return ResourceManager.GetString("VideoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexwert = {0:0.00}._Weiterlesen?.
        /// </summary>
        internal static string WaistHipMessage {
            get {
                return ResourceManager.GetString("WaistHipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist-Hip Index.
        /// </summary>
        internal static string WaistHipTitle {
            get {
                return ResourceManager.GetString("WaistHipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille.
        /// </summary>
        internal static string WaistString {
            get {
                return ResourceManager.GetString("WaistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woche.
        /// </summary>
        internal static string WeekString {
            get {
                return ResourceManager.GetString("WeekString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Körper.
        /// </summary>
        internal static string WeightControlString {
            get {
                return ResourceManager.GetString("WeightControlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewichtseingabebenachrichtigungen.
        /// </summary>
        internal static string WeightNotifyString {
            get {
                return ResourceManager.GetString("WeightNotifyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewicht.
        /// </summary>
        internal static string WeightString {
            get {
                return ResourceManager.GetString("WeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training nicht hinzugefügt. Das Dateiformat ist möglicherweise nicht korrekt..
        /// </summary>
        internal static string WorkoutAddedErrorString {
            get {
                return ResourceManager.GetString("WorkoutAddedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training hinzugefügt.
        /// </summary>
        internal static string WorkoutAddedString {
            get {
                return ResourceManager.GetString("WorkoutAddedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In der Anwendung ist die Erstellung von 3 Workouts begrenzt. Möchten Sie das Limit für 2,99 $ entfernen?.
        /// </summary>
        internal static string WorkoutLimitMessage {
            get {
                return ResourceManager.GetString("WorkoutLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahr.
        /// </summary>
        internal static string YearString {
            get {
                return ResourceManager.GetString("YearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string YesString {
            get {
                return ResourceManager.GetString("YesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select exercises for your superset by clicking the circles. Use the 'X' to remove an exercise from other supersets.
        /// </summary>
        internal static string SupersetAdvice {
            get {
                return ResourceManager.GetString("SupersetAdvice", resourceCulture);
            }
        }
    }
}
