//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDay.Maui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainingDay.Maui.Resources.Strings.AppResources.ru", typeof(AppResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достижения.
        /// </summary>
        internal static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление тренировки.
        /// </summary>
        internal static string AddTrainingString {
            get {
                return ResourceManager.GetString("AddTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Советы.
        /// </summary>
        internal static string Advice {
            get {
                return ResourceManager.GetString("Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заминка. 
        ///Заминка позволяет сгладить переход от высокоинтенсивной работы к состоянию покоя. Вы тем самым снижаете нагрузку на сердечную мышцу, которой приходится усиленно прокачивать кровь, чтобы убрать ее застой из мышц и снабдить ею внутренние органы. 
        ///Подойдут: 
        ///•Легкий бег, плавно переходящий в ходьбу (можно на месте). 
        ///•Легкая работа на вело- или эллиптическом тренажере
        ///•Прыжки на скакалке в небыстром темпе. 
        ///•Спарринг с грушей. 3 раунда по 2 минуты..
        /// </summary>
        internal static string AdviceAfterTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceAfterTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разминка.
        ///Комплекс упражнений для подготовки тела к физической нагрузке, который поможет вам: 
        ///• избежать травм и провести занятие максимально эффективно.
        ///• ускоряет метаболические процессы
        ///• улучшает кровообращение, что насытит ваши мышцы кислородом и питательными веществами
        ///• повысит выносливость во время занятий
        ///Разогретые мышцы лучше сжимаются и расслабляются во время тренировки, значит ваша силовые возможности во время выполнения упражнений будут выше. Подойдут базовые упражнения вроде махов руками, пр [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdviceBeforeTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceBeforeTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совет.
        /// </summary>
        internal static string AdviceString {
            get {
                return ResourceManager.GetString("AdviceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор: {0}.
        /// </summary>
        internal static string AuthorString {
            get {
                return ResourceManager.GetString("AuthorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to начинается с.
        /// </summary>
        internal static string BeginsAt {
            get {
                return ResourceManager.GetString("BeginsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить.
        /// </summary>
        internal static string BuyString {
            get {
                return ResourceManager.GetString("BuyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить выполнение тренировки?.
        /// </summary>
        internal static string CancelTrainingQuestion {
            get {
                return ResourceManager.GetString("CancelTrainingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения вступят в силу после перезапуска приложения.
        /// </summary>
        internal static string ChangesAcceptAfterReboot {
            get {
                return ResourceManager.GetString("ChangesAcceptAfterReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        internal static string ChooseGroupOrNewString {
            get {
                return ResourceManager.GetString("ChooseGroupOrNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие.
        /// </summary>
        internal static string ChoseAction {
            get {
                return ResourceManager.GetString("ChoseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить последнюю тренировку?.
        /// </summary>
        internal static string ContinueLastTrainingQuestion {
            get {
                return ResourceManager.GetString("ContinueLastTrainingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Копия.
        /// </summary>
        internal static string CopiedString {
            get {
                return ResourceManager.GetString("CopiedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирование упражнений завершено.
        /// </summary>
        internal static string CopyExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("CopyExercisesFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        internal static string CopyString {
            get {
                return ResourceManager.GetString("CopyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую.
        /// </summary>
        internal static string CreateNewString {
            get {
                return ResourceManager.GetString("CreateNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать суперсет.
        /// </summary>
        internal static string CreateSuperSetString {
            get {
                return ResourceManager.GetString("CreateSuperSetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий.
        /// </summary>
        internal static string CurrentString {
            get {
                return ResourceManager.GetString("CurrentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время: {0}.
        /// </summary>
        internal static string CurrentTimeString {
            get {
                return ResourceManager.GetString("CurrentTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd.MM.yyyy HH:mm:ss}.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дней.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалено.
        /// </summary>
        internal static string DeletedString {
            get {
                return ResourceManager.GetString("DeletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить упражнение?.
        /// </summary>
        internal static string DeleteExercise {
            get {
                return ResourceManager.GetString("DeleteExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить упражнение из суперсета?.
        /// </summary>
        internal static string DeleteExerciseFromSuperSetQuestion {
            get {
                return ResourceManager.GetString("DeleteExerciseFromSuperSetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить эту тренировку?.
        /// </summary>
        internal static string DeleteTraining {
            get {
                return ResourceManager.GetString("DeleteTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказано.
        /// </summary>
        internal static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние.
        /// </summary>
        internal static string DistanceString {
            get {
                return ResourceManager.GetString("DistanceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент различных упражнений: {0:0.0}%.
        /// </summary>
        internal static string DistinctExercisesPercentFormat {
            get {
                return ResourceManager.GetString("DistinctExercisesPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string DownloadingString {
            get {
                return ResourceManager.GetString("DownloadingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дублировать.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время: {0:hh\:mm\:ss}.
        /// </summary>
        internal static string ElapsedTimeString {
            get {
                return ResourceManager.GetString("ElapsedTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите email.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ник.
        /// </summary>
        internal static string EnterNick {
            get {
                return ResourceManager.GetString("EnterNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название тренировки и нажмите OK.
        /// </summary>
        internal static string EnterTrainingName {
            get {
                return ResourceManager.GetString("EnterTrainingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение.
        /// </summary>
        internal static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упражнение на .
        /// </summary>
        internal static string ExerciseForTypeString {
            get {
                return ResourceManager.GetString("ExerciseForTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упражнение есть в тренировках:.
        /// </summary>
        internal static string ExerciseInTrainings {
            get {
                return ResourceManager.GetString("ExerciseInTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упражнения.
        /// </summary>
        internal static string ExercisesString {
            get {
                return ResourceManager.GetString("ExercisesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по мышцам.
        /// </summary>
        internal static string FilterString {
            get {
                return ResourceManager.GetString("FilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыл пароль?.
        /// </summary>
        internal static string ForgotPasswordAction {
            get {
                return ResourceManager.GetString("ForgotPasswordAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цель.
        /// </summary>
        internal static string GoalString {
            get {
                return ResourceManager.GetString("GoalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понятно.
        /// </summary>
        internal static string GotItString {
            get {
                return ResourceManager.GetString("GotItString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без Группы.
        /// </summary>
        internal static string GroupingDefaultName {
            get {
                return ResourceManager.GetString("GroupingDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название группы.
        /// </summary>
        internal static string GroupingEnterNameofGroup {
            get {
                return ResourceManager.GetString("GroupingEnterNameofGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренировка уже в основной группе. .
        /// </summary>
        internal static string GroupingTrainingNotInGroup {
            get {
                return ResourceManager.GetString("GroupingTrainingNotInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полгода.
        /// </summary>
        internal static string HalfYearString {
            get {
                return ResourceManager.GetString("HalfYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, .
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОМОЩНИК.
        /// </summary>
        internal static string HelperString {
            get {
                return ResourceManager.GetString("HelperString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бедра.
        /// </summary>
        internal static string HipsString {
            get {
                return ResourceManager.GetString("HipsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполненные тренировки.
        /// </summary>
        internal static string HistoryTrainings {
            get {
                return ResourceManager.GetString("HistoryTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часов.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ч.
        /// </summary>
        internal static string HourString {
            get {
                return ResourceManager.GetString("HourString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупки в приложении.
        /// </summary>
        internal static string InAppPurchase {
            get {
                return ResourceManager.GetString("InAppPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  кг  .
        /// </summary>
        internal static string KilogramsString {
            get {
                return ResourceManager.GetString("KilogramsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнее выполнение: {0}.
        /// </summary>
        internal static string LastImplementedFormatString {
            get {
                return ResourceManager.GetString("LastImplementedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to фунты.
        /// </summary>
        internal static string LbsString {
            get {
                return ResourceManager.GetString("LbsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string LoginAction {
            get {
                return ResourceManager.GetString("LoginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти с Google.
        /// </summary>
        internal static string LoginWithGoogle {
            get {
                return ResourceManager.GetString("LoginWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string LogoutAction {
            get {
                return ResourceManager.GetString("LogoutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СТАРТ.
        /// </summary>
        internal static string MakeTrainingString {
            get {
                return ResourceManager.GetString("MakeTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметьте необходимые упражнения и нажмите кнопку {0}.
        /// </summary>
        internal static string MarkTheRequiredExercisesAndPressFormat {
            get {
                return ResourceManager.GetString("MarkTheRequiredExercisesAndPressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мера веса (кг или фунты).
        /// </summary>
        internal static string MeasureWeight {
            get {
                return ResourceManager.GetString("MeasureWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минут.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мин.
        /// </summary>
        internal static string MinuteString {
            get {
                return ResourceManager.GetString("MinuteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше года.
        /// </summary>
        internal static string MoreThanYearString {
            get {
                return ResourceManager.GetString("MoreThanYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самый частый день: {0:0}.
        /// </summary>
        internal static string MostOftenDayFormat {
            get {
                return ResourceManager.GetString("MostOftenDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОП упражнений.
        /// </summary>
        internal static string MostPopularExercises {
            get {
                return ResourceManager.GetString("MostPopularExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемещение тренировок завершено.
        /// </summary>
        internal static string MoveExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("MoveExercisesFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить.
        /// </summary>
        internal static string MoveString {
            get {
                return ResourceManager.GetString("MoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название: {0}.
        /// </summary>
        internal static string NameFormatString {
            get {
                return ResourceManager.GetString("NameFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        internal static string NewsString {
            get {
                return ResourceManager.GetString("NewsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать рекламу.
        /// </summary>
        internal static string NoAdsString {
            get {
                return ResourceManager.GetString("NoAdsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет упражнений по заданному фильтру..
        /// </summary>
        internal static string NoExercisesFilterString {
            get {
                return ResourceManager.GetString("NoExercisesFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет упражнений. Добавьте упражнение..
        /// </summary>
        internal static string NoExercisesNeedAddNewString {
            get {
                return ResourceManager.GetString("NoExercisesNeedAddNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще нет выполненных тренировок.
        /// </summary>
        internal static string NoLastTrainings {
            get {
                return ResourceManager.GetString("NoLastTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет напоминаний. Добавьте напоминание..
        /// </summary>
        internal static string NoNotificationsString {
            get {
                return ResourceManager.GetString("NoNotificationsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string NoString {
            get {
                return ResourceManager.GetString("NoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введены не все поля.
        /// </summary>
        internal static string NotAllFieldsEntered {
            get {
                return ResourceManager.GetString("NotAllFieldsEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще не выполнялась.
        /// </summary>
        internal static string NotExecutedYet {
            get {
                return ResourceManager.GetString("NotExecutedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напоминание.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет тренировок. Добавьте тренировку..
        /// </summary>
        internal static string NoTrainingsNeedAddNewString {
            get {
                return ResourceManager.GetString("NoTrainingsNeedAddNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать ограничение по тренировкам   .
        /// </summary>
        internal static string NoWorkoutLimit {
            get {
                return ResourceManager.GetString("NoWorkoutLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месяц.
        /// </summary>
        internal static string OneMounthString {
            get {
                return ResourceManager.GetString("OneMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум подрят недель с тренировками: {0:0}.
        /// </summary>
        internal static string OneTrainingPerWeekCountFormat {
            get {
                return ResourceManager.GetString("OneTrainingPerWeekCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для дней.
        /// </summary>
        internal static string OnTheseDays {
            get {
                return ResourceManager.GetString("OnTheseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Или.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите свой новый вес. Возможно что-то изменилось..
        /// </summary>
        internal static string PleaseEnterYourNewWeight {
            get {
                return ResourceManager.GetString("PleaseEnterYourNewWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мышцы пресса.
        /// </summary>
        internal static string PreparedAbdominalString {
            get {
                return ResourceManager.GetString("PreparedAbdominalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сильные руки.
        /// </summary>
        internal static string PreparedArmsStrength {
            get {
                return ResourceManager.GetString("PreparedArmsStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крепкая и рельефная спина.
        /// </summary>
        internal static string PreparedBackReady {
            get {
                return ResourceManager.GetString("PreparedBackReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кардио.
        /// </summary>
        internal static string PreparedCardioString {
            get {
                return ResourceManager.GetString("PreparedCardioString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фитнес.
        /// </summary>
        internal static string PreparedFitnessString {
            get {
                return ResourceManager.GetString("PreparedFitnessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сильные ноги и бедра.
        /// </summary>
        internal static string PreparedFootTraining {
            get {
                return ResourceManager.GetString("PreparedFootTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без инвентаря.
        /// </summary>
        internal static string PreparedHomeString {
            get {
                return ResourceManager.GetString("PreparedHomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная верхняя часть тела.
        /// </summary>
        internal static string PreparedMaximumUpperBody {
            get {
                return ResourceManager.GetString("PreparedMaximumUpperBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плоский живот.
        /// </summary>
        internal static string PreparedNiceStomach {
            get {
                return ResourceManager.GetString("PreparedNiceStomach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для начинающих.
        /// </summary>
        internal static string PreparedTrainingForBeginners {
            get {
                return ResourceManager.GetString("PreparedTrainingForBeginners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Широкие плечи.
        /// </summary>
        internal static string PreparedWideShoulders {
            get {
                return ResourceManager.GetString("PreparedWideShoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценить приложение.
        /// </summary>
        internal static string RateAppString {
            get {
                return ResourceManager.GetString("RateAppString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string RegisterAction {
            get {
                return ResourceManager.GetString("RegisterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string RemoveString {
            get {
                return ResourceManager.GetString("RemoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить каждые.
        /// </summary>
        internal static string RepeatEvery {
            get {
                return ResourceManager.GetString("RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить.
        /// </summary>
        internal static string RepeatString {
            get {
                return ResourceManager.GetString("RepeatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to повт.
        /// </summary>
        internal static string RepetitionsShort {
            get {
                return ResourceManager.GetString("RepetitionsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторения | Вес.
        /// </summary>
        internal static string RepsAndWeightString {
            get {
                return ResourceManager.GetString("RepsAndWeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторения.
        /// </summary>
        internal static string RepsString {
            get {
                return ResourceManager.GetString("RepsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перерыв.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить покупки.
        /// </summary>
        internal static string RestorePurchase {
            get {
                return ResourceManager.GetString("RestorePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы давно не выполняли тренировку. Может сегодня тот день?.
        /// </summary>
        internal static string ReturnToTrainingMessage {
            get {
                return ResourceManager.GetString("ReturnToTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранено.
        /// </summary>
        internal static string SavedString {
            get {
                return ResourceManager.GetString("SavedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить тренировку.
        /// </summary>
        internal static string SaveTrainingString {
            get {
                return ResourceManager.GetString("SaveTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экран должен быть включен при выполнении тренировки.
        /// </summary>
        internal static string ScreenOnWhenImplementing {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выключить для экономии батареи.
        /// </summary>
        internal static string ScreenOnWhenImplementingTip {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по названию.
        /// </summary>
        internal static string SearchByNameString {
            get {
                return ResourceManager.GetString("SearchByNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секунды.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сек.
        /// </summary>
        internal static string SecondString {
            get {
                return ResourceManager.GetString("SecondString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать все.
        /// </summary>
        internal static string SelectAllString {
            get {
                return ResourceManager.GetString("SelectAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать мышцы.
        /// </summary>
        internal static string SelectMusclesString {
            get {
                return ResourceManager.GetString("SelectMusclesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период.
        /// </summary>
        internal static string SelectPeriodString {
            get {
                return ResourceManager.GetString("SelectPeriodString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        internal static string SelectString {
            get {
                return ResourceManager.GetString("SelectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренировка:.
        /// </summary>
        internal static string SelectTraining {
            get {
                return ResourceManager.GetString("SelectTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить пароль.
        /// </summary>
        internal static string SendPassword {
            get {
                return ResourceManager.GetString("SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать частоту.
        /// </summary>
        internal static string SetFrequency {
            get {
                return ResourceManager.GetString("SetFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SettingsString {
            get {
                return ResourceManager.GetString("SettingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки тренировки.
        /// </summary>
        internal static string SettingsTrainingString {
            get {
                return ResourceManager.GetString("SettingsTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправлено.
        /// </summary>
        internal static string SharedString {
            get {
                return ResourceManager.GetString("SharedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться тренировкой.
        /// </summary>
        internal static string ShareTrainingString {
            get {
                return ResourceManager.GetString("ShareTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string ShortDescriptionString1 {
            get {
                return ResourceManager.GetString("ShortDescriptionString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать советы по разминке и заминке во время выполнения тренировки.
        /// </summary>
        internal static string ShowAdvicesOnImplementing {
            get {
                return ResourceManager.GetString("ShowAdvicesOnImplementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать подсказки.
        /// </summary>
        internal static string ShowToolTipsString {
            get {
                return ResourceManager.GetString("ShowToolTipsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропустить.
        /// </summary>
        internal static string SkipString {
            get {
                return ResourceManager.GetString("SkipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальная позиция.
        /// </summary>
        internal static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        internal static string StopString {
            get {
                return ResourceManager.GetString("StopString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление суперсетами.
        /// </summary>
        internal static string SuperSetControl {
            get {
                return ResourceManager.GetString("SuperSetControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суперсет создан.
        /// </summary>
        internal static string SuperSetCreatedMessage {
            get {
                return ResourceManager.GetString("SuperSetCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для создания Суперсета необходимо больше 2ух упражнений.
        /// </summary>
        internal static string SupersetInvalidMessage {
            get {
                return ResourceManager.GetString("SupersetInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суперсет.
        /// </summary>
        internal static string SuperSetString {
            get {
                return ResourceManager.GetString("SuperSetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация.
        /// </summary>
        internal static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены? Ваши несинхронизированные данные удалятся..
        /// </summary>
        internal static string SynchronizationDownloadingQuestion {
            get {
                return ResourceManager.GetString("SynchronizationDownloadingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация завершена с ошибкой.
        /// </summary>
        internal static string SynchronizationFinishedFailed {
            get {
                return ResourceManager.GetString("SynchronizationFinishedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация завершена успешно.
        /// </summary>
        internal static string SynchronizationFinishedSuccessful {
            get {
                return ResourceManager.GetString("SynchronizationFinishedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это упражнение уже есть в тренировке.
        /// </summary>
        internal static string ThisExerciseAlreadyInWorkoutMessage {
            get {
                return ResourceManager.GetString("ThisExerciseAlreadyInWorkoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Месяца.
        /// </summary>
        internal static string ThreeMounthString {
            get {
                return ResourceManager.GetString("ThreeMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string TimeString {
            get {
                return ResourceManager.GetString("TimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите на эту кнопку, чтобы добавить новую тренировку.
        /// </summary>
        internal static string ToolTipAddTrainingButton {
            get {
                return ResourceManager.GetString("ToolTipAddTrainingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта кнопка добавит подход для упражнения (Подход означает, сколько повторений вы будете делать упражнение с заданным весом).
        /// </summary>
        internal static string ToolTipAddWeightAndRepsString {
            get {
                return ResourceManager.GetString("ToolTipAddWeightAndRepsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта кнопка для отмены выполнения тренировки.
        /// </summary>
        internal static string ToolTipCancelImplementingTraining {
            get {
                return ResourceManager.GetString("ToolTipCancelImplementingTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите на нужные мышцы, чтобы отобразить упражнения для этих мышц.
        /// </summary>
        internal static string ToolTipFilterMuscle {
            get {
                return ResourceManager.GetString("ToolTipFilterMuscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта кнопка завершает выполнение упражнения.
        /// </summary>
        internal static string ToolTipFinishExercise {
            get {
                return ResourceManager.GetString("ToolTipFinishExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизуйтесь, чтобы была возможность синхронизироваться между устройствами..
        /// </summary>
        internal static string ToolTipGoogleSync {
            get {
                return ResourceManager.GetString("ToolTipGoogleSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы изменить порядок упражнений необходимо зажать изображение упражнение и тянуть до необходимой позиции..
        /// </summary>
        internal static string ToolTipHoldImageExercises {
            get {
                return ResourceManager.GetString("ToolTipHoldImageExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите на кнопку, чтобы выбрать упражнения для тренировки.
        /// </summary>
        internal static string ToolTipSelectExercisesToTrainingButton {
            get {
                return ResourceManager.GetString("ToolTipSelectExercisesToTrainingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта кнопка пропускает упражнение, это упражнение не будет отображаться в выполненных.
        /// </summary>
        internal static string ToolTipSkipExercise {
            get {
                return ResourceManager.GetString("ToolTipSkipExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите на эту кнопку, чтобы начать выполнение тренировки.
        /// </summary>
        internal static string ToolTipStartWorkout {
            get {
                return ResourceManager.GetString("ToolTipStartWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суперсет – это сочетание двухи более упражнений, рассчитанных на работу одной и той же мышцы либо мышц антагонистов. Наиболее распространенный способ применения суперсетов – это тренировка как раз разных по функциям мышечных групп. Например: бицепс/трицепс.
        /// </summary>
        internal static string ToolTipSuperSet {
            get {
                return ResourceManager.GetString("ToolTipSuperSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите и удерживайте на тренировке, чтобы увидеть настройки..
        /// </summary>
        internal static string ToolTipTapHoldTraining {
            get {
                return ResourceManager.GetString("ToolTipTapHoldTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполненных упражнений: {0:0}.
        /// </summary>
        internal static string TotalExercisesFormat {
            get {
                return ResourceManager.GetString("TotalExercisesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затраченное время:.
        /// </summary>
        internal static string TotalTimeSpent {
            get {
                return ResourceManager.GetString("TotalTimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполненных тренировок: {0:0}.
        /// </summary>
        internal static string TotalTrainingsFormat {
            get {
                return ResourceManager.GetString("TotalTrainingsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренировка завершена.
        /// </summary>
        internal static string TrainingFinishedString {
            get {
                return ResourceManager.GetString("TrainingFinishedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напоминания.
        /// </summary>
        internal static string TrainingNotifications {
            get {
                return ResourceManager.GetString("TrainingNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренировки.
        /// </summary>
        internal static string TrainingsBaseString {
            get {
                return ResourceManager.GetString("TrainingsBaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренировка.
        /// </summary>
        internal static string TrainingString {
            get {
                return ResourceManager.GetString("TrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в группу.
        /// </summary>
        internal static string TrainingToGroupString {
            get {
                return ResourceManager.GetString("TrainingToGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить из группы &quot;{0}&quot;.
        /// </summary>
        internal static string TrainingUnGroupString {
            get {
                return ResourceManager.GetString("TrainingUnGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 месяца.
        /// </summary>
        internal static string TwoMonthString {
            get {
                return ResourceManager.GetString("TwoMonthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 недели.
        /// </summary>
        internal static string TwoWeeksString {
            get {
                return ResourceManager.GetString("TwoWeeksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка.
        /// </summary>
        internal static string UploadingString {
            get {
                return ResourceManager.GetString("UploadingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string VideoString {
            get {
                return ResourceManager.GetString("VideoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение индекса = {0:0.00}._Хотите узнать больше?.
        /// </summary>
        internal static string WaistHipMessage {
            get {
                return ResourceManager.GetString("WaistHipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс талия-бедра.
        /// </summary>
        internal static string WaistHipTitle {
            get {
                return ResourceManager.GetString("WaistHipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Талия.
        /// </summary>
        internal static string WaistString {
            get {
                return ResourceManager.GetString("WaistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        internal static string WeekString {
            get {
                return ResourceManager.GetString("WeekString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фигура.
        /// </summary>
        internal static string WeightControlString {
            get {
                return ResourceManager.GetString("WeightControlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления о вводе веса.
        /// </summary>
        internal static string WeightNotifyString {
            get {
                return ResourceManager.GetString("WeightNotifyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес.
        /// </summary>
        internal static string WeightString {
            get {
                return ResourceManager.GetString("WeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренировка не добавлена. Возможно неправильный формат файла..
        /// </summary>
        internal static string WorkoutAddedErrorString {
            get {
                return ResourceManager.GetString("WorkoutAddedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренировка добавлена.
        /// </summary>
        internal static string WorkoutAddedString {
            get {
                return ResourceManager.GetString("WorkoutAddedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В приложении ограничение на создание 3ех тренировок. Хотите снять ограничение за $2.99?.
        /// </summary>
        internal static string WorkoutLimitMessage {
            get {
                return ResourceManager.GetString("WorkoutLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        internal static string YearString {
            get {
                return ResourceManager.GetString("YearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string YesString {
            get {
                return ResourceManager.GetString("YesString", resourceCulture);
            }
        }
    }
}
