//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDay.Maui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainingDay.Maui.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add workout.
        /// </summary>
        internal static string AddTrainingString {
            get {
                return ResourceManager.GetString("AddTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice and Tips.
        /// </summary>
        internal static string Advice {
            get {
                return ResourceManager.GetString("Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After workout, the post-workout routine is useful, the post-workout routine allows smoothing the transition from high-intensity work to a state of rest. You thereby reduce the burden on the heart muscle, which has to pump blood intensively, to remove its stagnation from the muscles and provide it with internal organs. Suitable: Easy running, smoothly turning into walking (you can in place). Easy work on a bicycle or elliptical simulator, a stepper with a smooth decrease in intensity up to a stop. Jumping on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdviceAfterTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceAfterTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretching before workout is a complex of exercises for preparing the body for physical activity, which will help you avoid injuries and conduct the session as efficiently as possible. Stretching speeds up metabolic processes. Stretching before exercise improves blood circulation, which will saturate your muscles with oxygen and nutrients. This will help improve endurance during class. The warmed muscles are better compressed and relax during workout, which means that your strengths will be higher during th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdviceBeforeTrainingMessage {
            get {
                return ResourceManager.GetString("AdviceBeforeTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice.
        /// </summary>
        internal static string AdviceString {
            get {
                return ResourceManager.GetString("AdviceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: {0}.
        /// </summary>
        internal static string AuthorString {
            get {
                return ResourceManager.GetString("AuthorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Workouts.
        /// </summary>
        internal static string BackToWorkouts {
            get {
                return ResourceManager.GetString("BackToWorkouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins at.
        /// </summary>
        internal static string BeginsAt {
            get {
                return ResourceManager.GetString("BeginsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string BuyString {
            get {
                return ResourceManager.GetString("BuyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel workout?.
        /// </summary>
        internal static string CancelTrainingQuestion {
            get {
                return ResourceManager.GetString("CancelTrainingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be accepted after restart application.
        /// </summary>
        internal static string ChangesAcceptAfterReboot {
            get {
                return ResourceManager.GetString("ChangesAcceptAfterReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string ChooseGroupOrNewString {
            get {
                return ResourceManager.GetString("ChooseGroupOrNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action.
        /// </summary>
        internal static string ChoseAction {
            get {
                return ResourceManager.GetString("ChoseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue last workout?.
        /// </summary>
        internal static string ContinueLastTrainingQuestion {
            get {
                return ResourceManager.GetString("ContinueLastTrainingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        internal static string CopiedString {
            get {
                return ResourceManager.GetString("CopiedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coping exercises completed.
        /// </summary>
        internal static string CopyExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("CopyExercisesFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyString {
            get {
                return ResourceManager.GetString("CopyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        internal static string CreateNewString {
            get {
                return ResourceManager.GetString("CreateNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SuperSet.
        /// </summary>
        internal static string CreateSuperSetString {
            get {
                return ResourceManager.GetString("CreateSuperSetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string CurrentString {
            get {
                return ResourceManager.GetString("CurrentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0}.
        /// </summary>
        internal static string CurrentTimeString {
            get {
                return ResourceManager.GetString("CurrentTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string DeletedString {
            get {
                return ResourceManager.GetString("DeletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this exercise?.
        /// </summary>
        internal static string DeleteExercise {
            get {
                return ResourceManager.GetString("DeleteExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete exercise from SuperSet?.
        /// </summary>
        internal static string DeleteExerciseFromSuperSetQuestion {
            get {
                return ResourceManager.GetString("DeleteExerciseFromSuperSetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this workout?.
        /// </summary>
        internal static string DeleteTraining {
            get {
                return ResourceManager.GetString("DeleteTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        internal static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string DifficultyAny {
            get {
                return ResourceManager.GetString("DifficultyAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string DifficultyEasy {
            get {
                return ResourceManager.GetString("DifficultyEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string DifficultyHard {
            get {
                return ResourceManager.GetString("DifficultyHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string DifficultyMedium {
            get {
                return ResourceManager.GetString("DifficultyMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different finished exercises: {0:0.0}%.
        /// </summary>
        internal static string DistinctExercisesPercentFormat {
            get {
                return ResourceManager.GetString("DistinctExercisesPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0:hh\:mm\:ss}.
        /// </summary>
        internal static string ElapsedTimeString {
            get {
                return ResourceManager.GetString("ElapsedTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter workout name and press OK.
        /// </summary>
        internal static string EnterTrainingName {
            get {
                return ResourceManager.GetString("EnterTrainingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution.
        /// </summary>
        internal static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise for .
        /// </summary>
        internal static string ExerciseForTypeString {
            get {
                return ResourceManager.GetString("ExerciseForTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise is in workouts:.
        /// </summary>
        internal static string ExerciseInTrainings {
            get {
                return ResourceManager.GetString("ExerciseInTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string ExercisesString {
            get {
                return ResourceManager.GetString("ExercisesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data to file.
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterString {
            get {
                return ResourceManager.GetString("FilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string GoalString {
            get {
                return ResourceManager.GetString("GoalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.
        /// </summary>
        internal static string GotItString {
            get {
                return ResourceManager.GetString("GotItString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string GroupingDefaultName {
            get {
                return ResourceManager.GetString("GroupingDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter group`s name.
        /// </summary>
        internal static string GroupingEnterNameofGroup {
            get {
                return ResourceManager.GetString("GroupingEnterNameofGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout already in Default group.
        /// </summary>
        internal static string GroupingTrainingNotInGroup {
            get {
                return ResourceManager.GetString("GroupingTrainingNotInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half year.
        /// </summary>
        internal static string HalfYearString {
            get {
                return ResourceManager.GetString("HalfYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELPER.
        /// </summary>
        internal static string HelperString {
            get {
                return ResourceManager.GetString("HelperString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hips.
        /// </summary>
        internal static string HipsString {
            get {
                return ResourceManager.GetString("HipsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past workouts.
        /// </summary>
        internal static string HistoryTrainings {
            get {
                return ResourceManager.GetString("HistoryTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string HourString {
            get {
                return ResourceManager.GetString("HourString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data from file.
        /// </summary>
        internal static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-App Purchase.
        /// </summary>
        internal static string InAppPurchase {
            get {
                return ResourceManager.GetString("InAppPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg .
        /// </summary>
        internal static string KilogramsString {
            get {
                return ResourceManager.GetString("KilogramsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last: {0}.
        /// </summary>
        internal static string LastImplementedFormatString {
            get {
                return ResourceManager.GetString("LastImplementedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbs.
        /// </summary>
        internal static string LbsString {
            get {
                return ResourceManager.GetString("LbsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s Build Your Workout.
        /// </summary>
        internal static string LetsBuildYourWorkout {
            get {
                return ResourceManager.GetString("LetsBuildYourWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string MakeTrainingString {
            get {
                return ResourceManager.GetString("MakeTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkmark the required exercises and press {0}.
        /// </summary>
        internal static string MarkTheRequiredExercisesAndPressFormat {
            get {
                return ResourceManager.GetString("MarkTheRequiredExercisesAndPressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure of weight (kg/lbs).
        /// </summary>
        internal static string MeasureWeight {
            get {
                return ResourceManager.GetString("MeasureWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string MinuteString {
            get {
                return ResourceManager.GetString("MinuteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than year.
        /// </summary>
        internal static string MoreThanYearString {
            get {
                return ResourceManager.GetString("MoreThanYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most often day: {0:0}.
        /// </summary>
        internal static string MostOftenDayFormat {
            get {
                return ResourceManager.GetString("MostOftenDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP exercises.
        /// </summary>
        internal static string MostPopularExercises {
            get {
                return ResourceManager.GetString("MostPopularExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving workouts finished.
        /// </summary>
        internal static string MoveExercisesFinishedMessage {
            get {
                return ResourceManager.GetString("MoveExercisesFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveString {
            get {
                return ResourceManager.GetString("MoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        internal static string NameFormatString {
            get {
                return ResourceManager.GetString("NameFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsString {
            get {
                return ResourceManager.GetString("NewsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your filter term of did not match any exercises.
        /// </summary>
        internal static string NoExercisesFilterString {
            get {
                return ResourceManager.GetString("NoExercisesFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exercises. You should add exercise..
        /// </summary>
        internal static string NoExercisesNeedAddNewString {
            get {
                return ResourceManager.GetString("NoExercisesNeedAddNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t done any workouts yet. Start your first workout!.
        /// </summary>
        internal static string NoLastTrainings {
            get {
                return ResourceManager.GetString("NoLastTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications. You should add notification..
        /// </summary>
        internal static string NoNotificationsString {
            get {
                return ResourceManager.GetString("NoNotificationsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoString {
            get {
                return ResourceManager.GetString("NoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all fields entered.
        /// </summary>
        internal static string NotAllFieldsEntered {
            get {
                return ResourceManager.GetString("NotAllFieldsEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not executed yet.
        /// </summary>
        internal static string NotExecutedYet {
            get {
                return ResourceManager.GetString("NotExecutedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workouts. You should add workout..
        /// </summary>
        internal static string NoTrainingsNeedAddNewString {
            get {
                return ResourceManager.GetString("NoTrainingsNeedAddNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string OneMounthString {
            get {
                return ResourceManager.GetString("OneMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum weeks with workout: {0:0}.
        /// </summary>
        internal static string OneTrainingPerWeekCountFormat {
            get {
                return ResourceManager.GetString("OneTrainingPerWeekCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On these days.
        /// </summary>
        internal static string OnTheseDays {
            get {
                return ResourceManager.GetString("OnTheseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new weight. Maybe something has changed..
        /// </summary>
        internal static string PleaseEnterYourNewWeight {
            get {
                return ResourceManager.GetString("PleaseEnterYourNewWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdominal.
        /// </summary>
        internal static string PreparedAbdominalString {
            get {
                return ResourceManager.GetString("PreparedAbdominalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong arms.
        /// </summary>
        internal static string PreparedArmsStrength {
            get {
                return ResourceManager.GetString("PreparedArmsStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong and embossed back.
        /// </summary>
        internal static string PreparedBackReady {
            get {
                return ResourceManager.GetString("PreparedBackReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biceps/Triceps Supersets.
        /// </summary>
        internal static string PreparedBicepsTricepsSuperSet {
            get {
                return ResourceManager.GetString("PreparedBicepsTricepsSuperSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio.
        /// </summary>
        internal static string PreparedCardioString {
            get {
                return ResourceManager.GetString("PreparedCardioString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        internal static string PreparedFitnessString {
            get {
                return ResourceManager.GetString("PreparedFitnessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong legs and thighs.
        /// </summary>
        internal static string PreparedFootTraining {
            get {
                return ResourceManager.GetString("PreparedFootTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Inventory.
        /// </summary>
        internal static string PreparedHomeString {
            get {
                return ResourceManager.GetString("PreparedHomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Upper Body.
        /// </summary>
        internal static string PreparedMaximumUpperBody {
            get {
                return ResourceManager.GetString("PreparedMaximumUpperBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning Workout.
        /// </summary>
        internal static string PreparedMorningWorkout {
            get {
                return ResourceManager.GetString("PreparedMorningWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Stomach.
        /// </summary>
        internal static string PreparedNiceStomach {
            get {
                return ResourceManager.GetString("PreparedNiceStomach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout for beginners.
        /// </summary>
        internal static string PreparedTrainingForBeginners {
            get {
                return ResourceManager.GetString("PreparedTrainingForBeginners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide Shoulders.
        /// </summary>
        internal static string PreparedWideShoulders {
            get {
                return ResourceManager.GetString("PreparedWideShoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate App.
        /// </summary>
        internal static string RateAppString {
            get {
                return ResourceManager.GetString("RateAppString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterAction {
            get {
                return ResourceManager.GetString("RegisterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string RemoveString {
            get {
                return ResourceManager.GetString("RemoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reps.
        /// </summary>
        internal static string RepetitionsShort {
            get {
                return ResourceManager.GetString("RepetitionsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions | Weight.
        /// </summary>
        internal static string RepsAndWeightString {
            get {
                return ResourceManager.GetString("RepsAndWeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions.
        /// </summary>
        internal static string RepsString {
            get {
                return ResourceManager.GetString("RepsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Purchase.
        /// </summary>
        internal static string RestorePurchase {
            get {
                return ResourceManager.GetString("RestorePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not implemented a workout for a long time. Maybe today is that day?.
        /// </summary>
        internal static string ReturnToTrainingMessage {
            get {
                return ResourceManager.GetString("ReturnToTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string SavedString {
            get {
                return ResourceManager.GetString("SavedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveTrainingString {
            get {
                return ResourceManager.GetString("SaveTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen should be turned on when doing a workout.
        /// </summary>
        internal static string ScreenOnWhenImplementing {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable to save battery.
        /// </summary>
        internal static string ScreenOnWhenImplementingTip {
            get {
                return ResourceManager.GetString("ScreenOnWhenImplementingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Name.
        /// </summary>
        internal static string SearchByNameString {
            get {
                return ResourceManager.GetString("SearchByNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string SecondString {
            get {
                return ResourceManager.GetString("SecondString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select muscles.
        /// </summary>
        internal static string SelectMusclesString {
            get {
                return ResourceManager.GetString("SelectMusclesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectString {
            get {
                return ResourceManager.GetString("SelectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsString {
            get {
                return ResourceManager.GetString("SettingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string SharedString {
            get {
                return ResourceManager.GetString("SharedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share workout.
        /// </summary>
        internal static string ShareTrainingString {
            get {
                return ResourceManager.GetString("ShareTrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warm-up and cool-down tips while doing a workout.
        /// </summary>
        internal static string ShowAdvicesOnImplementing {
            get {
                return ResourceManager.GetString("ShowAdvicesOnImplementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string SkipString {
            get {
                return ResourceManager.GetString("SkipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Position.
        /// </summary>
        internal static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopString {
            get {
                return ResourceManager.GetString("StopString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select exercises for your superset by clicking the circles. Use the &apos;X&apos; to remove an exercise from other supersets..
        /// </summary>
        internal static string SupersetAdvice {
            get {
                return ResourceManager.GetString("SupersetAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet Control.
        /// </summary>
        internal static string SuperSetControl {
            get {
                return ResourceManager.GetString("SuperSetControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet created.
        /// </summary>
        internal static string SuperSetCreatedMessage {
            get {
                return ResourceManager.GetString("SuperSetCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a Superset you need more than 2 exercises.
        /// </summary>
        internal static string SupersetInvalidMessage {
            get {
                return ResourceManager.GetString("SupersetInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet.
        /// </summary>
        internal static string SuperSetString {
            get {
                return ResourceManager.GetString("SuperSetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? Your unsynchronized data will be deleted..
        /// </summary>
        internal static string SynchronizationDownloadingQuestion {
            get {
                return ResourceManager.GetString("SynchronizationDownloadingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Month.
        /// </summary>
        internal static string ThreeMounthString {
            get {
                return ResourceManager.GetString("ThreeMounthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TimeString {
            get {
                return ResourceManager.GetString("TimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button to add a new workout.
        /// </summary>
        internal static string ToolTipAddTrainingButton {
            get {
                return ResourceManager.GetString("ToolTipAddTrainingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button will add a set for the exercise (Set means how many reps you will do the exercise with a given weight).
        /// </summary>
        internal static string ToolTipAddWeightAndRepsString {
            get {
                return ResourceManager.GetString("ToolTipAddWeightAndRepsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button cancels the workout..
        /// </summary>
        internal static string ToolTipCancelImplementingTraining {
            get {
                return ResourceManager.GetString("ToolTipCancelImplementingTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the desired muscle to apply a filter for those muscles.
        /// </summary>
        internal static string ToolTipFilterMuscle {
            get {
                return ResourceManager.GetString("ToolTipFilterMuscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button ends the exercise..
        /// </summary>
        internal static string ToolTipFinishExercise {
            get {
                return ResourceManager.GetString("ToolTipFinishExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the order of the exercises, you need to hold the image of the exercise and drag it to the desired position..
        /// </summary>
        internal static string ToolTipHoldImageExercises {
            get {
                return ResourceManager.GetString("ToolTipHoldImageExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button to select exercises for workout.
        /// </summary>
        internal static string ToolTipSelectExercisesToTrainingButton {
            get {
                return ResourceManager.GetString("ToolTipSelectExercisesToTrainingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button skips the exercise, this exercise will not appear in completed.
        /// </summary>
        internal static string ToolTipSkipExercise {
            get {
                return ResourceManager.GetString("ToolTipSkipExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button to start your workout.
        /// </summary>
        internal static string ToolTipStartWorkout {
            get {
                return ResourceManager.GetString("ToolTipStartWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet is a combination of two or more exercises designed to work the same muscle or muscles of the antagonists. The most common way to use supersets is to train muscle groups with different functions. For example: biceps / triceps.
        /// </summary>
        internal static string ToolTipSuperSet {
            get {
                return ResourceManager.GetString("ToolTipSuperSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press and hold on a workout to see settings..
        /// </summary>
        internal static string ToolTipTapHoldTraining {
            get {
                return ResourceManager.GetString("ToolTipTapHoldTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished exercises: {0:0}.
        /// </summary>
        internal static string TotalExercisesFormat {
            get {
                return ResourceManager.GetString("TotalExercisesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time spent:.
        /// </summary>
        internal static string TotalTimeSpent {
            get {
                return ResourceManager.GetString("TotalTimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished workouts: {0:0}.
        /// </summary>
        internal static string TotalTrainingsFormat {
            get {
                return ResourceManager.GetString("TotalTrainingsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string TrainingNotifications {
            get {
                return ResourceManager.GetString("TrainingNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        internal static string TrainingsBaseString {
            get {
                return ResourceManager.GetString("TrainingsBaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        internal static string TrainingString {
            get {
                return ResourceManager.GetString("TrainingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to group.
        /// </summary>
        internal static string TrainingToGroupString {
            get {
                return ResourceManager.GetString("TrainingToGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Group &quot;{0}&quot;.
        /// </summary>
        internal static string TrainingUnGroupString {
            get {
                return ResourceManager.GetString("TrainingUnGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 month.
        /// </summary>
        internal static string TwoMonthString {
            get {
                return ResourceManager.GetString("TwoMonthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 weeks.
        /// </summary>
        internal static string TwoWeeksString {
            get {
                return ResourceManager.GetString("TwoWeeksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index value = {0:0.00}._Read more?.
        /// </summary>
        internal static string WaistHipMessage {
            get {
                return ResourceManager.GetString("WaistHipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist-Hip Index.
        /// </summary>
        internal static string WaistHipTitle {
            get {
                return ResourceManager.GetString("WaistHipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string WaistString {
            get {
                return ResourceManager.GetString("WaistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string WeekString {
            get {
                return ResourceManager.GetString("WeekString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string WeightControlString {
            get {
                return ResourceManager.GetString("WeightControlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight entry notifications.
        /// </summary>
        internal static string WeightNotifyString {
            get {
                return ResourceManager.GetString("WeightNotifyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string WeightString {
            get {
                return ResourceManager.GetString("WeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking this button, the user will show or hide exercises with barbells..
        /// </summary>
        internal static string WithBarbell {
            get {
                return ResourceManager.GetString("WithBarbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking this button, the user will show or hide exercises with dumbbells..
        /// </summary>
        internal static string WithDumbbell {
            get {
                return ResourceManager.GetString("WithDumbbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking this button, the user will show or hide exercises without equipment (home-friendly)..
        /// </summary>
        internal static string WithoutEquipment {
            get {
                return ResourceManager.GetString("WithoutEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout not added. The file format may not be correct..
        /// </summary>
        internal static string WorkoutAddedErrorString {
            get {
                return ResourceManager.GetString("WorkoutAddedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout added.
        /// </summary>
        internal static string WorkoutAddedString {
            get {
                return ResourceManager.GetString("WorkoutAddedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout almost created.
        /// </summary>
        internal static string WorkoutAlmostCreated {
            get {
                return ResourceManager.GetString("WorkoutAlmostCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string YearString {
            get {
                return ResourceManager.GetString("YearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesString {
            get {
                return ResourceManager.GetString("YesString", resourceCulture);
            }
        }
    }
}
